name: project deployment
on: 
  push:
    branches: [main]
jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest
    steps: 
      - name: run ssh
        uses: appleboy/ssh-action@v1
        with:
          host: 183.101.189.204
          username: test
          password: qwer1234
          port: 127
          script:
            rm -rf ./docker-practice
            git clone https://github.com/tipsyboy/docker-practice.git
            cd ./docker-practice
            chmod 755 ./gradlew
            ./gradlew bootJar
            docker rm -f back
            docker image prune -f
            docker build --tag tipsyboy/back:latest .
            docker run -d --name back -p 8080:8080 tipsyboy/back:latest